import styles from './home/Home.module.css';

export default function Home() {
    return (
        <div className={styles.container}>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/public/favicon.ico" />
        </div>
    )
}
